### ISSUE TITLE
Не верный пакет

### ISSUE THREAD

**Issue by ShvetsovYura** [praktikum-game/defence-game#16]
в файле `src/components/AppRoutes/AppRoutes.tsx` импортируется `react-router`, которого нет в package.json. Наверно нужно импортирвать `react-router-dom`

**Comment by ShvetsovYura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить работу с React Router.](https://trello.com/c/r1pC6iau/7-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83-%D1%81-react-router)

**Comment by diglibum** [comment]
#17  fixed, нужно бы влить

**Comment by ShvetsovYura** [comment]
fixed
