### ISSUE TITLE
Валидация при регистрации

### ISSUE THREAD

**Issue by ShvetsovYura** [praktikum-game/defence-game#40]
На странице регистрации не работает повторная валидация пароля (выдается сообщение под подклем, что пароли не совадают), и, соответственно не активируетя кнопка регистрации. 
Пока код активации кноки закоментил.

**Comment by Verisana** [comment]
На `main` убираю комменты с `disabled` и проблема не воспроизводится. Пароли на совпадение проверяются корректно. Там, единственно, не все проверки были, я их пофиксил. Попробуй, пожалуйста, еще раз.

**Comment by Verisana** [comment]
@ShvetsovYura  затэгаю, чтобы увидел

**Comment by ShvetsovYura** [comment]
Я видел. Мельком проверил - вроде работает. Теперь у меня проблема возникал при регистарции =) (но это уже наверно, сервисная тема)

**Comment by ShvetsovYura** [comment]
Тебе надо было все-таки в PR это сделать и самому его влить, как фикс. Сейчас бы закрытие issue свазяли бы с этим  PR.
