### ISSUE TITLE
Ошибка при входе на форум

### ISSUE THREAD

**Issue by ShvetsovYura** [praktikum-game/defence-game#73]
Если на форум входит незалогиненный пользователь, то выскакивает ошибка.

![image](https://user-images.githubusercontent.com/43341468/150779530-e4ce54b8-5370-441c-88b6-6866106092c3.png)

**Comment by ShvetsovYura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Исправить переход на форум](https://trello.com/c/loYnM1f0/132-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4-%D0%BD%D0%B0-%D1%84%D0%BE%D1%80%D1%83%D0%BC)

**Comment by Verisana** [comment]
Странно, у меня нет этой проблемы на проде. Как ее воспроизвести? Еще вполне вероятно, что она уйдет после моего последнего ПР. Там некоторые пробелмы с форумом исправил.

**Comment by Verisana** [comment]
@ShvetsovYura 
Это еще актуально?
